### ISSUE TITLE
#define deltat

### ISSUE THREAD

**Issue by a-kozlov-msu** [p-o-n-y/ExamplePonyApp-madgwick#1]
ExampleApp.c

Уберём лишние дефайны и хардкод

#define deltat 1/250. 

нужно убрать, а частоту записи (sampling rate) 250 добавить в конфигурацию, она может быть разной; deltat вычислять в фильтре при инициализации

**Comment by osenmukdav** [comment]
Что делаем значением по умолчанию?

**Comment by a-kozlov-msu** [comment]
Тут не придумать стандартного значения. Если этого нет в конфгурации, значит в исходных данных есть время, и по приращению определяется deltat. Можно условно взять 100 Гц, но логики никакой в этом нет, в отличие от других случаев. Например, нули и единицы в качестве параметров калибровки означают, что на входе данные уже предварительно откалиброваны и т.д.

**Comment by a-kozlov-msu** [comment]
Так. Вообще deltat нужно переименовать в dt и положить на шину. Инициализировать как инвалидные данные и проверять при использовании. Так будет правильно в общем случае. Потому что dt может меняться, и у меня много таких записей. Конкретно для этой переменной по умолчанию ничего быть не может. Даже для имени файла есть смысл указывать что-то типа "imu.txt" в качестве входного файла, потому что тогда программу с неверной конфигурацией всё равно можно будет использовать по назначению. С dt такого нет.
