### ISSUE TITLE
#define gyroMeasError

### ISSUE THREAD

**Issue by a-kozlov-msu** [p-o-n-y/ExamplePonyApp-madgwick#2]
ExampleApp.c

#define gyroMeasError 3.14159265358979f * (5.0f / 180.0f)
тоже убрать и задавать в конфигурации 5 град/сек (это переменный параметр, который можно подбирать); 
по умолчанию это же значение; 
пересчитывать в радианы в секунду (3.14159265358979f заменить на M_PI) при инициализации фильтра

**Comment by osenmukdav** [comment]
Исправил
