### ISSUE TITLE
calibr w[0] = (w[0] - Awx)/Mwx

### ISSUE THREAD

**Issue by a-kozlov-msu** [p-o-n-y/ExamplePonyApp-madgwick#5]
ExampleApp.c 
void calibr(void)

для угловых скоростей пересчёт должен быть такой:

w[0] = (w[0] - Awx)/Mwx*(M_PI/180);

соответственно, Mw.. изменятся в конфигурации; 

это традиция задавать углы исходно в градусах, время - в секундах; перевод в радианы * (M_PI/180) стандартен; сейчас смысл числа 648000 неочевиден; раньше это было 180 * 3600, где множитель 180 - это часть перевода в радианы, а 3600 - перевод из градусов в час в градусы в секунду.

**Comment by osenmukdav** [comment]
Заменил формулы и домножил Mw... на 3600, но появились различия в данных. Это должно быть настолько сильно?
out.txt - файл до изменения формулы.
out (2).txt - файл после изменения формулы
[out.txt](https://github.com/p-o-n-y/ExamplePonyApp-madgwick/files/3101544/out.txt)
[out (2).txt](https://github.com/p-o-n-y/ExamplePonyApp-madgwick/files/3101545/out.2.txt)

**Comment by a-kozlov-msu** [comment]
Я сейчас не могу посмотреть файлы, но отличий быть не должно (в пределах машинной точности или её последствий). В дебаге надо сравнить итоговые преобразования показаний датчиков, может в одном косяк всего, например.

Или напиши значения конечного кватерниона сюда, может я прикину.

**Comment by a-kozlov-msu** [comment]
Судя по данным, больше похоже просто на ошибку. Надо проверять.

**Comment by a-kozlov-msu** [comment]
Разрешилось?

**Comment by osenmukdav** [comment]
С sscanf'ом та же проблема, что и с atof, так что придётся писать свою функцию для считывания float'ов и double'ов.

**Comment by a-kozlov-msu** [comment]
Что за проблема? Что не так со считыванием? Я забыл.
